const header=document.querySelector('.site-header');addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>20));
const mt=document.querySelector('.menu-toggle'),nav=document.querySelector('.site-header nav');mt.addEventListener('click',()=>{const o=nav.classList.toggle('open');mt.setAttribute('aria-expanded',o)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));
const hero=document.querySelector('.hero-visual');if(hero&&matchMedia('(pointer:fine)').matches)hero.addEventListener('mousemove',e=>{const r=hero.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;hero.querySelector('.mock').style.transform=`rotateY(${x*8-7}deg) rotateX(${-y*6+3}deg) translate(${x*5}px,${y*5}px)`});
const faq=[['Ile kosztuje strona?','Prosta strona firmowa zaczyna się od około 1200 zł. Dokładną cenę ustalam przed rozpoczęciem prac.'],['Ile trwa wykonanie?','Zależy od wielkości strony i materiałów. Termin ustalamy przed rozpoczęciem.'],['Nie mam domeny ani hostingu. Co wtedy?','Nie szkodzi. Pomogę je wybrać, skonfigurować i uruchomić stronę.'],['Mam już stronę. Możesz ją tylko poprawić?','Tak. Nie zawsze trzeba robić wszystko od początku.'],['Czy później możesz zajmować się stroną?','Tak. Mogę aktualizować treści, zdjęcia, realizacje i wykonywać bieżące poprawki.'],['Czy pracujesz tylko na Śląsku?','Nie. Lokalnie działam głównie na Śląsku, ale projekty mogę realizować zdalnie w całej Polsce.'],['Czy robisz sklepy?','Tak, realizuję również proste sklepy internetowe. Zakres wyceniam indywidualnie.']];document.querySelector('.accordion').innerHTML=faq.map(([q,a])=>`<div class="faq-item"><button class="faq-q" aria-expanded="false">${q}<span>+</span></button><div class="faq-a"><p>${a}</p></div></div>`).join('');document.querySelectorAll('.faq-q').forEach(b=>b.onclick=()=>{const i=b.parentElement,o=i.classList.toggle('open');b.setAttribute('aria-expanded',o);b.querySelector('span').textContent=o?'−':'+'});
const tl=document.querySelector('.timeline'),prog=document.querySelector('.timeline-progress');addEventListener('scroll',()=>{if(!tl)return;const r=tl.getBoundingClientRect(),p=Math.max(0,Math.min(1,(innerHeight*.65-r.top)/(r.height*.8)));prog.style.height=p*100+'%'});
const qc=document.querySelector('.quick-contact'),qb=qc.querySelector('button');qb.onclick=()=>{const o=qc.classList.toggle('open');qb.setAttribute('aria-expanded',o)};document.addEventListener('click',e=>{if(!qc.contains(e.target)){qc.classList.remove('open');qb.setAttribute('aria-expanded','false')}});document.getElementById('year').textContent=new Date().getFullYear();

// Cookie consent — only stores the user's choice locally. Add optional analytics/marketing scripts only after consent.
const cookiePopup=document.getElementById('cookiePopup');
const cookieChoice=localStorage.getItem('iwnCookieConsent');
if(cookiePopup&&cookieChoice)cookiePopup.classList.add('hidden');
document.querySelector('.cookie-accept')?.addEventListener('click',()=>{localStorage.setItem('iwnCookieConsent','accepted');cookiePopup?.classList.add('hidden')});
document.querySelector('.cookie-essential')?.addEventListener('click',()=>{localStorage.setItem('iwnCookieConsent','essential');cookiePopup?.classList.add('hidden')});

